In [0]:
!pip install tensorflow==1.5.0

In [0]:
import tensorflow as tf

node1 = tf.constant(3, dtype=tf.int32)
node2 = tf.constant(5, dtype=tf.int32)
node3 = tf.add(node1, node2)

with tf.Session() as sess:
    print("node1 + node2 = ", sess.run(node3))

node1 + node2 =  8


- Example: Placeholder (p21)

In [0]:
#import tensorflow as tf
a = tf.placeholder(tf.int32, shape=(3, 1))
b = tf.placeholder(tf.int32, shape=(1, 3))
c = tf.matmul(a, b)

with tf.Session() as sess:
    print(sess.run(c, feed_dict={a: [[3], [2], [1]], b: [[1, 2, 3]]}))

[[3 6 9]
 [2 4 6]
 [1 2 3]]


https://wikidocs.net/7635

https://gdyoon.tistory.com/9?category=703363


- Linear Regression Implementation (TensorFlow) (p34)


In [0]:
x_data = [[1,1], [2,2], [3,3]]
y_data = [[10], [20], [30]]
X = tf.placeholder(tf.float32, shape=[None, 2])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([2,1]))
b = tf.Variable(tf.random_normal([1]))

model = tf.matmul(X,W)+b
cost = tf.reduce_mean(tf.square(model - Y))
train = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    # Training
    for step in range(2001):
        c, W_, b_, _ = sess.run([cost, W, b, train], feed_dict={X: x_data, Y: y_data})
        print(step, c, W_, b_)
    # Tesintg
        print(sess.run(model, feed_dict={X: [[4,4]]}))

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
[[39.446564]]
335 0.08029855 [[4.5599914]
 [5.115183 ]] [0.74731547]
[[39.448013]]
336 0.079879604 [[4.5604157]
 [5.1156073]] [0.74536216]
[[39.449455]]
337 0.07946279 [[4.560839 ]
 [5.1160307]] [0.743414]
[[39.450897]]
338 0.07904782 [[4.5612617]
 [5.116453 ]] [0.74147093]
[[39.45233]]
339 0.0786353 [[4.5616827]
 [5.116874 ]] [0.73953295]
[[39.45376]]
340 0.07822401 [[4.562103 ]
 [5.1172943]] [0.7376]
[[39.45519]]
341 0.077816315 [[4.562522 ]
 [5.1177135]] [0.7356721]
[[39.45661]]
342 0.07740944 [[4.5629396]
 [5.118131 ]] [0.7337493]
[[39.45803]]
343 0.07700537 [[4.5633564]
 [5.118548 ]] [0.73183143]
[[39.459446]]
344 0.076603435 [[4.563772 ]
 [5.1189637]] [0.72991866]
[[39.46086]]
345 0.0762033 [[4.5641866]
 [5.119378 ]] [0.72801083]
[[39.462273]]
346 0.07580627 [[4.5646   ]
 [5.1197915]] [0.726108]
[[39.463673]]
347 0.0754097 [[4.5650125]
 [5.120204 ]] [0.7242102]
[[39.465076]]
348 0.07501654 [[4.565424 ]
 [5.1206155]] [0.72231734]
[[39.466473]]
3

learning rate가 너무 크면 overshooting
              , 너무 작으면 시간이 많이 걸림
- Binary Classification Implementation (p55)

            

In [0]:
x_data = [[1,1], [2,3], [3,1], [4,3], [5,3], [6,2]]
y_data = [[0], [0], [0], [1], [1], [1]]
X = tf.placeholder(tf.float32, shape=[None, 2])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([2,1]))
b = tf.Variable(tf.random_normal([1]))

model = tf.sigmoid(tf.add(tf.matmul(X,W),b))
cost = tf.reduce_mean((-1)*Y*tf.log(model) + (-1)*(1-Y)*tf.log(1-model))
train = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

prediction = tf.cast(model > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(prediction, Y), dtype=tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    # Training
    for step in range(10001):
        cost_val, train_val = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})
        if step % 1000 == 0:
            print(step, cost_val)
    # Tesintg
    h, c, a = sess.run([model, prediction, accuracy], feed_dict={X: x_data, Y: y_data})
    print("\nModel: ", h,"\nCorrect: ", c, "\nAccuracy:", a)



스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
5016 0.17354043
5017 0.17352487
5018 0.17350918
5019 0.17349361
5020 0.17347802
5021 0.17346244
5022 0.17344683
5023 0.17343122
5024 0.17341568
5025 0.1734001
5026 0.17338449
5027 0.17336889
5028 0.17335331
5029 0.17333774
5030 0.17332214
5031 0.17330658
5032 0.17329104
5033 0.17327546
5034 0.17325993
5035 0.17324437
5036 0.17322882
5037 0.17321326
5038 0.17319773
5039 0.17318217
5040 0.17316659
5041 0.17315108
5042 0.17313553
5043 0.17311998
5044 0.17310447
5045 0.17308895
5046 0.1730734
5047 0.17305791
5048 0.17304242
5049 0.17302687
5050 0.17301136
5051 0.17299585
5052 0.17298035
5053 0.17296486
5054 0.17294933
5055 0.17293383
5056 0.17291836
5057 0.17290282
5058 0.17288737
5059 0.17287189
5060 0.17285639
5061 0.17284091
5062 0.1728255
5063 0.17281
5064 0.1727945
5065 0.17277908
5066 0.17276359
5067 0.17274815
5068 0.17273265
5069 0.1727172
5070 0.17270172
5071 0.1726863
5072 0.17267083
5073 0.17265539
5074 0.17263997
5075 0.17262454
5076 0.172609

- Softmax Classification Implementation (TensorFlow) (p73)

In [0]:
import tensorflow as tf

x_data = [[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]] #vectors
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]] # one hot encoding
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 3])
W = tf.Variable(tf.random_normal([4,3]))
b = tf.Variable(tf.random_normal([3]))

model_LC = tf.add(tf.matmul(X,W),b)
model = tf.nn.softmax(model_LC)
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=model_LC, labels=Y))
#cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(model), reduction_indices=1))

train = tf.train.GradientDescentOptimizer(0.1).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    # Training
    for step in range(2001):
        c, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})
        print(step, c)
    # Tesintg
    test1 = sess.run(model, feed_dict={X: [[1,11,7,9]]})
    print(test1, sess.run(tf.argmax(test1, 1)))  #argmax(...,1) 1은 가로축으로 
    #

0 8.343379
1 6.847827
2 5.368395
3 3.8957644
4 2.4354694
5 1.2147381
6 1.0032599
7 0.9187814
8 0.9031553
9 0.9328479
10 0.90606207
11 0.97909033
12 0.8637299
13 0.9584082
14 0.83340096
15 0.9301852
16 0.80998063
17 0.9039072
18 0.7899972
19 0.8798351
20 0.7725804
21 0.85805297
22 0.75727904
23 0.83846915
24 0.74380195
25 0.8209574
26 0.73191833
27 0.80536425
28 0.72143126
29 0.7915236
30 0.71216345
31 0.77926356
32 0.70396054
33 0.7684195
34 0.6966839
35 0.7588358
36 0.6902127
37 0.7503693
38 0.6844423
39 0.74289346
40 0.67927897
41 0.7362913
42 0.6746431
43 0.7304581
44 0.6704629
45 0.72529954
46 0.6666773
47 0.72073025
48 0.6632318
49 0.7166735
50 0.66007835
51 0.71305764
52 0.6571747
53 0.70982045
54 0.6544833
55 0.70690453
56 0.6519736
57 0.7042619
58 0.649616
59 0.7018465
60 0.647388
61 0.6996212
62 0.6452676
63 0.69755304
64 0.6432385
65 0.695614
66 0.64128554
67 0.69378066
68 0.63939714
69 0.6920337
70 0.6375623
71 0.69035554
72 0.63577247
73 0.68873346
74 0.63402194
75 0.687157

In [0]:
# tf.argmax
# 두 번째 파라미터는 one-hot-encoding을 적용할 차원을 알려주는 매개변수이다. 
#1차원 배열에 대해서는 0, 2차원 배열에 대해서는 0과 1, 3차원 배열에 대해서는 0, 1, 2를 사용할 수 있다.

