MNIST



In [0]:
!pip install tensorflow==1.5.0

In [0]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data", one_hot=True)
import tensorflow as tf
import numpy as np


In [0]:
tf.__version__

'1.5.0'

KNN (MNIST활용)


In [0]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data", one_hot=True)
import tensorflow as tf
import numpy as np

n_train_img = 5000
n_test_img = 200
pixel_train, onehot_train = mnist.train.next_batch(n_train_img)
pixel_test, onehot_test = mnist.train.next_batch(n_test_img)

TRAIN = tf.placeholder("float", [None, 784] )
TEST = tf.placeholder("float", [784] )  

#맨하탄 디스턴스
d = tf.reduce_sum(tf.abs(tf.add(TRAIN, tf.negative(TEST))), reduction_indices=1)   #tb.abs (절대값)    |x1 - x2| + |y1 - y2| + |z1 - z2|......, reduction_indices는 axis랑 동일의미
#Euclidean 디스턴스
#d =  tf.sqrt(tf.reduce_sum(tf.square(tf.abs(tf.add(TRAIN, tf.negative(TEST)))), reduction_indices=1))

val, idx = tf.nn.top_k(-d, k=5, sorted=False) 
acc = 0.0

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(n_test_img):
        knn_idx = sess.run(idx, feed_dict={TRAIN: pixel_train, TEST: pixel_test[i,:]})  #거리가 가까운 5개의 index [3580 1097 4597 2554 3177] ....test수만큼
        look_up = np.zeros(10)
        for j in np.argmax(onehot_train[knn_idx], axis=1):  # np.argmax 최대값 색인찾기
            look_up[j] += 1
        pred = np.argmax(look_up)

        print("Test:", i)
        print("Pred:", pred, "Real:" , np.argmax(onehot_test[i]))
        if pred == np.argmax(onehot_test[i]):
            acc += 1./n_test_img           #####?????          
    print("Accuracy:", acc)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Test: 0
Pred: 4 Real: 4
Test: 1
Pred: 7 Real: 7
Test: 2
Pred: 6 Real: 6
Test: 3
Pred: 1 Real: 1
Test: 4
Pred: 8 Real: 8
Test: 5
Pred: 1 Real: 1
Test: 6
Pred: 9 Real: 4
Test: 7
Pred: 4 Real: 9
Test: 8
Pred: 1 Real: 1
Test: 9
Pred: 9 Real: 9
Test: 10
Pred: 2 Real: 2
Test: 11
Pred: 0 Real: 0
Test: 12
Pred: 6 Real: 6
Test: 13
Pred: 4 Real: 4
Test: 14
Pred: 9 Real: 9
Test: 15
Pred: 6 Real: 6
Test: 16
Pred: 1 Real: 1
Test: 17
Pred: 9 Real: 9
Test: 18
Pred: 4 Real: 4
Test: 19
Pred: 4 Real: 4
Test: 20
Pred: 7 Real: 7
Test: 21
Pred: 9 Real: 9
Test: 22
Pred: 2 Real: 2
Test: 23
Pred: 0 Real: 0
Test: 24
Pred: 5 Real: 5
Test: 25
Pred: 6 Real: 6
Test: 26
Pred: 4 Real: 4
Test: 27
Pred: 9 Real: 9
Test: 28
Pred: 6 Real: 6
Test: 29
Pred: 0 Real: 0
Test: 30
Pred: 7 Real: 7
Test: 31
Pred: 0 Real: 0
Test: 32
Pred: 0

In [0]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data", one_hot=True)
import tensorflow as tf
import numpy as np

n_train_img = 5000
n_test_img = 200
pixel_train, onehot_train = mnist.train.next_batch(n_train_img)
pixel_test, onehot_test = mnist.train.next_batch(n_test_img)

TRAIN = tf.placeholder("float", [None, 784] )
TEST = tf.placeholder("float", [784] )  

#맨하탄 디스턴스
d = tf.reduce_sum(tf.abs(tf.add(TRAIN, tf.negative(TEST))), reduction_indices=1)   #tb.abs (절대값)    |x1 - x2| + |y1 - y2| + |z1 - z2|......, reduction_indices는 axis랑 동일의미
#Euclidean 디스턴스
#d =  tf.sqrt(tf.reduce_sum(tf.square(tf.abs(tf.add(TRAIN, tf.negative(TEST)))), reduction_indices=1))

val, idx = tf.nn.top_k(-d, k=5, sorted=False) 

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(n_test_img):
        knn_idx = sess.run(idx, feed_dict={TRAIN: pixel_train, TEST: pixel_test[i,:]})
        print(knn_idx)
        print(np.argmax(onehot_train[knn_idx], axis=1))



Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
[ 595 3362 4743 3950 3322]
[6 6 6 6 6]
[3395 1616  462  406  959]
[6 6 6 6 6]
[3742 1240 2509 2297 2302]
[5 5 3 5 6]
[ 677 1334 3924 1664 3513]
[4 4 4 4 4]
[2256 2748 4691 1393 1539]
[4 4 4 4 4]
[1415 3066 2365 2118  768]
[7 4 2 2 2]
[2741 2186 4833  202 1921]
[4 4 4 4 4]
[1385  705 3560  763  180]
[9 9 9 9 9]
[4195 3501 4387 2491  215]
[1 1 1 1 1]
[3216  780 4538 2407 1564]
[9 7 7 9 9]
[3413 3890 4853 4420 1940]
[5 3 5 3 5]
[1446 1103 3296 1532 1410]
[7 7 7 7 7]
[1443 2929 4111  103 1080]
[5 5 5 5 5]
[2891 2411 3923 2697 2141]
[8 8 8 8 8]
[4873  779 1921 2800 1287]
[4 4 4 4 4]
[1032 2634 4947  288 4341]
[8 5 8 8 3]
[1880 1113 4226  545  124]
[4 9 4 9 4]
[ 547 3453 3421 2430 1404]
[1 1 1 1 1]
[4345  700 4023 2578 3450]
[4 9 4 9 9]
[2706  523 3436 1092 4398]
[1 1 1 1 1]
[ 711 1180 4638 1362  158]

In [0]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data", one_hot=True)
import tensorflow as tf
import numpy as np

n_train_img = 5

pixel_train, onehot_train = mnist.train.next_batch(n_train_img)

print(pixel_train,onehot_train)



Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] [[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
